config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shedule.urls", namespace="shedule"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shedule/urls.py
from shedule.apps import SheduleConfig
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from shedule.views.client import ClientsListView, ClientCreateView, ClientUpdateView, ClientDeleteView
from shedule.views.mailing_attempt import MailingAttemptListView
from shedule.views.newsletter import NewsletterListView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView
from shedule.views.text_for_newsletter import TextForNewsletterListView, TextForNewsletterCreateView, \
    TextForNewsletterUpdateView, TextForNewsletterDeleteView

app_name = SheduleConfig.name

urlpatterns = [
    path("", MailingAttemptListView.as_view(), name="mailingattempt_list"),

    path("client_list/", ClientsListView.as_view(), name="client_list"),
    path("client_form/", ClientCreateView.as_view(), name="client_form"),
    path("<int:pk>/client_update", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/client_delete", ClientDeleteView.as_view(), name="client_delete"),

    path("newsletter_list/", NewsletterListView.as_view(), name="newsletter_list"),
    path("newsletter_form/", NewsletterCreateView.as_view(), name="newsletter_form"),
    path("<int:pk>/newsletter_update", NewsletterUpdateView.as_view(), name="newsletter_update"),
    path("<int:pk>/newsletter_delete", NewsletterDeleteView.as_view(), name="newsletter_delete"),

    path("textfornewsletter_list/", TextForNewsletterListView.as_view(), name="textfornewsletter_list"),
    path("textfornewsletter_form/", TextForNewsletterCreateView.as_view(), name="textfornewsletter_form"),
    path("<int:pk>/textfornewsletter_update", TextForNewsletterUpdateView.as_view(), name="textfornewsletter_update"),
    path("<int:pk>/textfornewsletter_delete", TextForNewsletterDeleteView.as_view(), name="textfornewsletter_delete"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shedule/models.py
from django.db import models

CREATE = 'Создана'
STARTED = 'Отправлено'
DONE = 'Завершена'

DAILY = 'раз в день'
WEEKLY = 'раз в неделю'
MONTHLY = 'раз в месяц'

FREQUENCY_CHOICES = [('Ежедневно', DAILY), ('Еженедельно', WEEKLY), ('Ежемесячно', MONTHLY), ]
STATUS_OF_NEWSLETTER = [("Создать", CREATE), ("Запустить", STARTED), ("Завершить", DONE), ]


class Client(models.Model):
    contact_email = models.CharField(max_length=250, verbose_name='контактный email')
    fullname = models.TextField(verbose_name='фио')
    comment = models.CharField(max_length=250, verbose_name='комментарий')

    def __str__(self):
        return f"{self.contact_email} {self.fullname} {self.comment}"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class TextForNewsletter(models.Model):
    subject = models.CharField(max_length=200, verbose_name='тема')
    text = models.TextField(verbose_name='текст')

    def __str__(self):
        return f"{self.subject} {self.text}"

    class Meta:
        verbose_name = "Текст для отправки"
        verbose_name_plural = "Тексты для рассылок"


class Newsletter(models.Model):
    start_time = models.DateTimeField(verbose_name='время начала рассылки', blank=True, null=True)
    end_time = models.DateTimeField(verbose_name='время окончания рассылки', blank=True, null=True)
    frequency = models.CharField(max_length=300, choices=FREQUENCY_CHOICES, verbose_name="Частота отправки")
    status_of_newsletter = models.CharField(max_length=150, verbose_name='статус рассылки',
                                            choices=STATUS_OF_NEWSLETTER)
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    message = models.ForeignKey(TextForNewsletter, on_delete=models.CASCADE, verbose_name='Сообщение для отправки')

    def __str__(self):
        return f"{self.start_time} {self.end_time} {self.frequency} {self.status_of_newsletter} {self.clients} {self.message}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingAttempt(models.Model):
    time_attempt = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True, blank=True,
                                        null=True)
    status_of_last_attempt = models.BooleanField(verbose_name='Статус попытки', blank=True,
                                                 null=True)

    clients_list = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиенты для рассылки', blank=True,
                                     null=True)
    mailing_list = models.ForeignKey(Newsletter, on_delete=models.CASCADE, verbose_name='Письма для рассылки',
                                     blank=True,
                                     null=True)

    server_response = models.CharField(verbose_name='ответ почтового сервера', blank=True, null=True)

    def __str__(self):
        return f" {self.status_of_last_attempt} {self.clients_list} {self.mailing_list} {self.server_response} {self.time_attempt}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"

shedule/forms.py
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from django import forms

from shedule.models import Newsletter


class MixinForms(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class NewsletterForm(MixinForms):
    class Meta:
        model = Newsletter
        fields = ['start_time', 'end_time', 'frequency', 'clients', 'message']
        widgets = {
            'start_time': DateTimePickerInput(options={"format": "YYYY-MM-DD HH:mm", "showClose": True}),
            'end_time': DateTimePickerInput(options={"format": "YYYY-MM-DD HH:mm", "showClose": True}),
        }

shedule/views/client.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from shedule.models import Client


class ClientsListView(ListView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    fields = ('contact_email', 'fullname', 'comment',)
    success_url = reverse_lazy("shedule:client_list")


class ClientUpdateView(UpdateView):
    model = Client
    fields = ('contact_email', 'fullname', 'comment',)
    def get_success_url(self):
        return reverse("shedule:client_list")


class ClientDeleteView(DeleteView):
    model = Client

    def get_success_url(self):
        return reverse("shedule:client_list")

shedule/views/mailing_attempt.py
from django.urls import reverse
from django.views.generic import ListView

from shedule.models import MailingAttempt, Newsletter


class MailingAttemptListView(ListView):
    model = MailingAttempt

    def get_success_url(self):
        return reverse("shedule:mailingattempt_list")

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        return context_data

shedule/views/newsletter.py
from bootstrap_datepicker_plus.widgets import DateTimePickerInput, DatePickerInput
from django.db.models import Prefetch
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from shedule.forms import NewsletterForm
from shedule.models import Newsletter


class NewsletterListView(ListView):
    model = Newsletter


class NewsletterCreateView(CreateView):
    model = Newsletter
    form_class = NewsletterForm

    success_url = reverse_lazy("shedule:newsletter_list")

    def form_valid(self, form):
        newsletter = form.save(commit=False)

        selected_clients = form.cleaned_data.get('clients')

        newsletter.save()

        newsletter.clients.clear()

        for client in selected_clients:
            newsletter.clients.add(client)

        # Возвращаем успешный ответ
        return super().form_valid(form)


class NewsletterUpdateView(UpdateView):
    model = Newsletter
    form_class = NewsletterForm

    def get_success_url(self):
        return reverse("shedule:newsletter_list")

    def form_valid(self, form):
        # Получаем объект формы, но еще не сохраняем его в базу данных
        newsletter = form.save(commit=False)

        # Получаем выбранных клиентов из данных формы
        selected_clients = form.cleaned_data.get('clients')

        # Сохраняем объект формы в базу данных
        newsletter.save()

        # Очищаем связанных клиентов, чтобы избежать дублирования
        newsletter.clients.clear()

        # Добавляем выбранных клиентов к объекту Newsletter
        for client in selected_clients:
            newsletter.clients.add(client)
        print(newsletter)

        # Возвращаем успешный ответ
        return super().form_valid(form)


class NewsletterDeleteView(DeleteView):
    model = Newsletter

    def get_success_url(self):
        return reverse("shedule:newsletter_list")

shedule/views/text_for_newsletter.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from shedule.models import TextForNewsletter


class TextForNewsletterListView(ListView):
    model = TextForNewsletter


class TextForNewsletterCreateView(CreateView):
    model = TextForNewsletter
    fields = ('subject', 'text',)
    success_url = reverse_lazy("shedule:textfornewsletter_list")


class TextForNewsletterUpdateView(UpdateView):
    model = TextForNewsletter
    fields = ('subject', 'text',)

    def get_success_url(self):
        return reverse("shedule:textfornewsletter_list")


class TextForNewsletterDeleteView(DeleteView):
    model = TextForNewsletter

    def get_success_url(self):
        return reverse("shedule:textfornewsletter_list")

shedule/templates/shedule/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM - админка</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'shedule:client_list' %}">Клиенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'shedule:textfornewsletter_list' %}">Посты для рассылок</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'shedule:newsletter_list' %}">Настройка рассылок</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'shedule:mailingattempt_list' %}">Статусы</a>
    </nav>
</div>
{% block content %}
{% endblock %}
</div>

shedule/templates/shedule/client_confirm_delete.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Создание статьи</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <form method="post" enctype="multipart/form-data">
                        <div class="card shadow">
                            <div class="card-body">
                                {% csrf_token %}
                                <p class="text-center mb-4">Вы уверены, что хотите удалить: {{ object.fullname }}</p>
                                <div class="d-grid gap-2">
                                    <button type="submit" class="btn btn-danger btn-lg">
                                        Удалить
                                    </button>
                                    <a type="button" class="btn btn-primary btn-lg mt-2" href="{% url 'shedule:client_list' %}">
                                        Отменить
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

shedule/templates/shedule/client_form.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
        <h1 class="display-4">Создание клиента</h1>
    </div>
    <main>
        <div class="album py-2 bg-body-tertiary">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <form method="post" enctype="multipart/form-data">
                        <div class="card shadow-md">
                            <div class="card-body">
                                {% csrf_token %}
                                <div class="mb-3">
                                    {{ form.as_p }}
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-center">
                                <button type="submit" class="btn btn-success me-2">
                                    {% if object %}
                                        Изменить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                                <a class="btn btn-secondary ms-2"
                                   href="{% url 'shedule:client_list' %}">
                                    Отменить
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

shedule/templates/shedule/client_list.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Список клиентов
        <div class="float-end">
            <a type="button" class="btn btn-lg btn-block btn-outline-success"
               href="{% url 'shedule:client_form' %}">
                Создать
            </a>
        </div>
    </h1>
</div>
<main>
    <div class="album py-4 bg-body-tertiary">
        <div class="container text-start">
            {% for client in object_list %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ client.fullname }}
                    </h5>
                    <p class="card-text">
                        {{ client.contact_email }}
                    <p>{{ client.comment }}</p>
                    <a type="button" class="btn btn-sm btn-block btn-outline-primary"
                       href="{% url 'shedule:client_update' client.pk %}">
                        Изменить
                    </a>
                    <a type="button" class="btn btn-sm btn-block btn-outline-danger"
                       href="{% url 'shedule:client_delete' client.pk %}">
                        Удалить
                    </a>
                </div>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>

    </div>
</main>
{% endblock %}

shedule/templates/shedule/mailingattempt_list.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-3 mx-auto text-center">
    <h1 class="display-4">Вся информация
    </h1>
</div>
<form action="" class="form-floating">
    <div class="row">
        <div class="col-3 p-4">
            <div class="card mb-3 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        Статусы рассылок: </h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-6">
                    </ul>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

shedule/templates/shedule/newsletter_confirm_delete.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Создание статьи</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1">
                <div class="col">
                    <form class="row" method="post" enctype="multipart/form-data">
                        <div class="card shadow-lg">
                            <div class="card-body">
                                {% csrf_token %}
                                Вы уверены, что хотите удалить: {{ object.message.subject }}
                            </div>
                            <div class="col">
                                <div class="row-3 py-3">
                                    <button type="submit" class="btn btn-sm btn-block btn-outline-danger">
                                        Удалить
                                    </button>
                                    <a type="button" class="btn btn-sm btn-block btn-outline-primary"
                                       href="{% url 'shedule:newsletter_list' %}">
                                        Отменить
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

shedule/templates/shedule/newsletter_form.html
{% extends 'shedule/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
        <h1 class="display-4">Создание рассылки</h1>
    </div>
    <main>
        <div class="album py-2 bg-body-tertiary">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <form method="post" enctype="multipart/form-data">
                        <div class="card shadow-md">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.media }}
                                <div class="mb-3">
                                    {{ form.as_p }}
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-center">
                                <button type="submit" class="btn btn-success me-2">
                                    {% if object %}
                                    Изменить
                                    {% else %}
                                    Создать
                                    {% endif %}
                                </button>
                                <a class="btn btn-secondary ms-2"
                                   href="{% url 'shedule:client_list' %}">
                                    Отменить
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

shedule/templates/shedule/newsletter_list.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Настройка рассылок
        <div class="float-end">
            <a type="button" class="btn btn-lg btn-block btn-outline-success"
               href="{% url 'shedule:newsletter_form' %}">
                Создать
            </a>
        </div>
    </h1>
</div>
<main>
    <div class="album py-4 bg-body-tertiary">
        <div class="container text-start">
            {% for news in object_list %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        Статус рассылки: {{ news.status_of_newsletter }}
                    </h5>
                    <p class="card-text">
                        {{ news.message.subject }}
                    <p>{{ news.frequency }}</p>
                    <p>{{ news.status_of_newsletter }}</p>
                    <a type="button" class="btn btn-sm btn-block btn-outline-primary"
                       href="{% url 'shedule:newsletter_update' news.pk %}">
                        Изменить
                    </a>
                    <a type="button" class="btn btn-sm btn-block btn-outline-danger"
                       href="{% url 'shedule:newsletter_delete' news.pk %}">
                        Удалить
                    </a>
                </div>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>

    </div>
</main>
{% endblock %}

shedule/templates/shedule/textfornewsletter_confirm_delete.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Создание статьи</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1">
                <div class="col">
                    <form class="row" method="post" enctype="multipart/form-data">
                        <div class="card shadow-lg">
                            <div class="card-body">
                                {% csrf_token %}
                                Вы уверены, что хотите удалить: {{ object.subject }}
                            </div>
                            <div class="col">
                                <div class="row-3 py-3">
                                    <button type="submit" class="btn btn-sm btn-block btn-outline-danger">
                                        Удалить
                                    </button>
                                    <a type="button" class="btn btn-sm btn-block btn-outline-primary"
                                       href="{% url 'shedule:textfornewsletter_list' %}">
                                        Отменить
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

shedule/templates/shedule/textfornewsletter_form.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
        <h1 class="display-4">Создание текста для рассылки</h1>
    </div>
    <main>
        <div class="album py-2 bg-body-tertiary">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <form method="post" enctype="multipart/form-data">
                        <div class="card shadow-md">
                            <div class="card-body">
                                {% csrf_token %}
                                <div class="mb-3">
                                    {{ form.as_p }}
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-center">
                                <button type="submit" class="btn btn-success me-2">
                                    {% if object %}
                                        Изменить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                                <a class="btn btn-secondary ms-2"
                                   href="{% url 'shedule:client_list' %}">
                                    Отменить
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

shedule/templates/shedule/textfornewsletter_list.html
{% extends 'shedule/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h1 class="display-4">Посты для рассылок
        <div class="float-end">
            <a type="button" class="btn btn-lg btn-block btn-outline-success"
               href="{% url 'shedule:textfornewsletter_form' %}">
                Создать
            </a>
        </div>
    </h1>
</div>
<main>
    <div class="album py-4 bg-body-tertiary">
        <div class="container text-start">
            {% for text in object_list %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ text.subject }}
                    </h5>
                    <p class="card-text">
                        {{ text.text }}</p>
                    <a type="button" class="btn btn-sm btn-block btn-outline-primary"
                       href="{% url 'shedule:textfornewsletter_update' text.pk %}">
                        Изменить
                    </a>
                    <a type="button" class="btn btn-sm btn-block btn-outline-danger"
                       href="{% url 'shedule:textfornewsletter_delete' text.pk %}">
                        Удалить
                    </a>
                </div>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>

    </div>
</main>
{% endblock %}